---
# tasks file for roles/loadbalancers
- name: Installing services
  yum:
    name:
    - httpd
    - php
    state: present
    
- name: Check if apache works
  service:
    name: httpd
    state: started
    enabled: yes