---
# tasks file for roles/webservers
- name: Install apache
  yum:
    name: httpd
    state: present

- name: Check if apache works
  service:
    name: httpd
    state: started
    enabled: yes

- name: Upload application file
  copy:
    src: ../files/hello.html
    dest: /var/www/html
    mode: 0755

- name: Create index.html
  copy:
    dest: /var/www/html/index.html
    content: "<h1>Hello {{ ansible_hostname }}</h1>"